### PR TITLE
add callback support and fix tests

### LINKED ISSUE #3: No callback after beeps have finished
I use beeper before I call `process.exit()`.

Because of beeper's `setTimeout()`s, if I `require('beeper')(5); process.exit();` I only hear one beep. This is on Windows, by the way.

If beeper checked for the last element in `arguments` being a function and treated that like a callback, I could do this, and hear 5 beeps:

    require('beeper')(5, function() {
        process.exit();
    });

Alternatively, beeper could return a promise so I could instead do:

    `require('beeper')(5).then(process.exit);`

I can submit a PR if this idea is tenable.

### LINKED ISSUE #7: Test is broken: beep - count
This test does not check that there are 3 beeps.

The test suite passes both before my pull request #6 and after, even though it beeps twice before and three times after.

### PR DESCRIPTION
**Pull request by sindresorhus**
fixes #3
fixes #7

### CODE REVIEW

**Comment by sindresorhus** [comment]
@tremby would you mind reviewing?

**Comment by tremby** [comment]
Callback works for me, called at the right time, so #3 looks good.
Test now fails if it beeps more or fewer times than expected, so #7 looks good.

I noticed something else, though, which I'll fix in a new PR.

**Comment by tremby** [comment]
Actually no, there is a bug, #3 is not good. If called with 1, it beeps once but the callback does not fire.

**Comment by sindresorhus** [comment]
> Actually no, there is a bug, #3 is not good. If called with 1, it beeps once but the callback does not fire.

Should be fixed.

-

Lgty?

**Comment by tremby** [comment]
Yes. I'm about to open another PR which builds on this one.

**Pull request merged**
