### PR TITLE
Fix number of beeps

### PR DESCRIPTION
**Pull request by tremby**
Before this commit beeper(n) beeps max(1, n-1) times rather than n.

### CODE REVIEW

**Comment by sindresorhus** [comment]
`node -e "require('./')(3)"` beeps 3 times for me, so not sure what you're saying is wrong. Can you provide an example?

**Comment by tremby** [comment]
It only beeps twice for me before my patch.

```
$ time node -e "require('./')(3)"
node -e "require('./')(3)"  0.04s user 0.01s system 10% cpu 0.558 total
```

The wait time beween beeps is 500ms, so clearly it has only beeped once at the start and once at the end of a single wait.

https://github.com/sindresorhus/beeper/blob/master/index.js#L33

Say `val` starts as 3.

There's a beep on line 34, then val is decremented on line 35.

`val` is now 2.

When the loop starts on line 37 `val` is checked (it's 2, truthy) and is decremented again, to 1.

On this first loop we set a timeout for a beep for 500 * 1 ms.

The loop check runs again (it's 1, truthy) and `val` is decremented to 0.

On this second loop we set a timeout for a beep for 500 * 0 ms.

So yes, it beeps three times, but two are at exactly the same time (immediately).

The loop checks again, but the value is 0 so the loop stops. `val` is decremented to -1.

**Comment by tremby** [comment]
I've pushed a revised version which is a clearer fix.

**Comment by tremby** [comment]
...and again. Now we decrement before checking the value. This makes more sense, I think.

**Comment by sindresorhus** [comment]
You're right. Thanks for elaborating :)

**Pull request merged**
